// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCDCyhi2DojBKOc4vBKefZu1ZjPEJF0A4',
    appId: '1:1067133688805:web:2487757367828dafbded0c',
    messagingSenderId: '1067133688805',
    projectId: 'social-media-e99cc',
    authDomain: 'social-media-e99cc.firebaseapp.com',
    storageBucket: 'social-media-e99cc.appspot.com',
    measurementId: 'G-0HK2TGCDBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1BX17jpJfR4dFrTdtKIifApVcWn-RK8',
    appId: '1:1067133688805:android:1e7af50c92134055bded0c',
    messagingSenderId: '1067133688805',
    projectId: 'social-media-e99cc',
    storageBucket: 'social-media-e99cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHUMKEIzyjaS9Q-6i1iou-kukV7dyBz94',
    appId: '1:1067133688805:ios:3b282583012b41e3bded0c',
    messagingSenderId: '1067133688805',
    projectId: 'social-media-e99cc',
    storageBucket: 'social-media-e99cc.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHUMKEIzyjaS9Q-6i1iou-kukV7dyBz94',
    appId: '1:1067133688805:ios:3b282583012b41e3bded0c',
    messagingSenderId: '1067133688805',
    projectId: 'social-media-e99cc',
    storageBucket: 'social-media-e99cc.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3YK9MGiiYgJmR_MmqNoNctxfjZYBUs-Q',
    appId: '1:1067133688805:web:3cfe9df6e9f9b4c2bded0c',
    messagingSenderId: '1067133688805',
    projectId: 'social-media-e99cc',
    authDomain: 'social-media-e99cc.firebaseapp.com',
    storageBucket: 'social-media-e99cc.appspot.com',
    measurementId: 'G-1Q6DPTGK7N',
  );

}